{
 "title": "Beaglebone",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "ssh_cpu_usage_percent", "legendFormat": "CPU Usage %" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Total Memory: 483 MB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "ssh_memory_used_percent" }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "description": "Disk Size: 3.44 GB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "ssh_root_disk_usage_percent" }
   ]
  },
  {
   "title": "Device Online/Offline Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"ssh-exporter\"}"
    }
   ]
  }
 ]
}